Remove token refresh
MoveOnOrg/python-controlshift pull request #5
Opened 2024-03-19 17:49 UTC by technicalex

After lots of investigation and conversation with ControlShift support, I believe our intermittent issues connecting from Turtle  to ControlShift have two causes: CSL servers do not support token refresh, and we were persisting each session indefinitely. 

Here are some snippets from my conversation from ControlShift support:
* "I checked the configuration of [doorkeeper](https://github.com/doorkeeper-gem/doorkeeper) (the ruby gem we use for providing OAuth authentication) and it seems like it's not currently set up to generate refresh tokens when issuing the first access token. Could it be possible from your side to, each time an access token expires, request a new token using the initial process instead of requesting using a refresh token?"
* "Is it possible that the code you've written opens a long running http connection over many individual requests, but doesn't handle reopening the connection if it is closed in the middle of a long-running piece of custom application code? It is not necessarily a bug if the other end of a long running http connection is closed by the peer."

Instead of persisting the session indefinitely and refreshing the token automatically, we now create a session for each request to ControlShift, and manually create a new token when the existing one expires or the connection is reset.

One future improvement would be to support a single session for a pre-defined batch of get requests (e.g. when we are running the refresh petition cron job). Another future improvement would be to retry more than once, instead of only handling a single failure. But, I think the approach below will solve most of the errors we currently encounter.

These changes are deployed to the Turtle staging environment. You can search the relevant logs for the string "CSL Auth:" to see the changes in action. I recommend that we deploy these changes to Turtle prod after they are approved but before they are merged, in case we need to make additional changes.

2024-03-20 00:10 UTC, strangeways requested changes
Thanks for figuring this out! These changes makes sense, now that we know CSL doesn't support auto-refreshing tokens. Can you remove the comment about `toker_saver()`? (lines 28-30; GitHub won't let me add a response there)

2024-03-20 15:55 UTC, technicalex commented
> Thanks for figuring this out! These changes makes sense, now that we know CSL doesn't support auto-refreshing tokens. Can you remove the comment about toker_saver()? (lines 28-30; GitHub won't let me add a response there)

@strangeways, I totally forgot about the original token saver code! Thanks for pointing it out. I'm actually wondering if I should put back all the token saver code, rather than remove the documentation about it. I removed it because my first approach involved generating a new token for each call (a plan that was foiled by rate limits). But since we went back to saving the token after all, it might be good to preserve the feature that lets clients store the token elsewhere? On the other hand, I'm not sure if it's as useful to store the token if it's not going to auto-refresh. What do you think?

2024-03-20 20:22 UTC, strangeways commented
> @strangeways, I totally forgot about the original token saver code! Thanks for pointing it out. I'm actually wondering if I should put back all the token saver code, rather than remove the documentation about it. I removed it because my first approach involved generating a new token for each call (a plan that was foiled by rate limits). But since we went back to saving the token after all, it might be good to preserve the feature that lets clients store the token elsewhere? On the other hand, I'm not sure if it's as useful to store the token if it's not going to auto-refresh. What do you think?

Either way is fine with me, since I don't think this is used anywhere other than Turtle. I'd lean toward putting it back in to facilitate future improvements and in case CSL does eventually support auto-refresh.

2024-03-20 22:07 UTC, technicalex commented
> I'd lean toward putting it back in to facilitate future improvements and in case CSL does eventually support auto-refresh.

That makes sense to me! Thank you. I'm going to push the change here so I can pull it into my local environment. If it works there, I'll deploy to staging and post an update.

2024-03-20 22:25 UTC, technicalex commented
These changes worked locally, and are now deployed to staging! They appear to be working there, too. I'll keep an eye on the logs.

2024-03-20 23:09 UTC, strangeways approved these changes
👍

2024-03-21 14:43 UTC, sjwmoveon approved these changes

2024-03-21 15:51 UTC, technicalex commented
Thank you both for your review! I will deploy to production now and monitor today/tomorrow before merging.

2024-03-22 20:03 UTC, technicalex commented
This appears to be working! There have been no errors on production or staging since the changes were deployed, respectively, and no issues reported by stakeholders. Merging now!

2024-03-22 20:03 UTC, merged